
/* V20 field-work patch */
(function(){
  const V20='20.0';
  function escV20(x){return typeof esc19==='function'?esc19(x):String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function keyV20(x){return window.formKey?window.formKey(x):String(x||'').trim()}
  function dataUrlBytes(u){const b=atob(String(u).split(',')[1]||'');const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
  function watermarkedUTM(file,utmInfo,pointId){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const max=2200,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);const fs=Math.max(18,Math.round(w/72));ctx.font=`700 ${fs}px Arial`;ctx.textAlign='left';const lines=[`پایش منابع آب | ${pointId}`,`UTM: ${utmInfo.zone}${utmInfo.hemisphere} | E ${Number(utmInfo.e).toFixed(2)} | N ${Number(utmInfo.n).toFixed(2)}`,`تاریخ: ${utmInfo.date} ${utmInfo.time}`],pad=16,bh=fs*1.45*lines.length+pad*2;ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,h-bh,w,bh);ctx.fillStyle='#fff';lines.forEach((x,i)=>ctx.fillText(x,pad,h-bh+pad+fs*(i+1)*1.25));resolve(c.toDataURL('image/jpeg',.92))};img.onerror=reject;img.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
  async function collectPhotoFilesV20(){const out=[];const cam=document.getElementById('photosCamera');const gal=document.getElementById('photosGallery');for(const f of [...(cam?.files||[]),...(gal?.files||[])])out.push(f);return out}
  function renderV20Special(p){const host=document.getElementById('specialHost');if(!host)return;const t=keyV20(document.getElementById('type')?.value),d=window.FORM_DEFS[t];host.innerHTML=d?`<div class="card special-one"><div class="sectionTitle"><h3>📋 فرم تخصصی همین نقطه: ${escV20(t)}</h3><span class="badge">یک فرم واحد</span></div><div class="two">${window.formFieldsGlobal(d,p&&p.pointType===t?p.specialData||{}:{})}</div></div>`:''}
  window.newPoint=function(editId){
    const p=editId?db.points.find(x=>x.pointId===editId):null,opts=db.rivers.filter(r=>r.active).map(r=>`<option value="${r.id}" ${p&&p.riverId===r.id?'selected':''}>${escV20(r.name)}</option>`).join('');
    const types=[...new Set([...(window.TYPES||[]),...Object.keys(window.FORM_DEFS)])];
    app.innerHTML=`<div class="card"><div class="sectionTitle"><h2>${p?'✏️ ویرایش نقطه':'📍 ثبت نقطه جدید'}</h2><span class="badge">V20 | فرم میدانی</span></div>
      <label>رودخانه</label><select id="river">${opts}</select>
      <div class="row"><button onclick="getGPS()">📍 دریافت GPS</button><span id="gpsmsg" class="muted">مختصات واقعی گوشی دریافت می‌شود.</span></div>
      <div class="two compact-gps">
        <div><label>Latitude</label><input id="lat" inputmode="decimal" value="${p?.latitude??''}"></div><div><label>Longitude</label><input id="lon" inputmode="decimal" value="${p?.longitude??''}"></div>
        <div><label>UTM Zone</label><input id="zone" inputmode="numeric" value="${p?.utmZone??39}"></div><div><label>Hemisphere</label><select id="hemi"><option value="N" ${p?.utmHemisphere!=='S'?'selected':''}>N</option><option value="S" ${p?.utmHemisphere==='S'?'selected':''}>S</option></select></div>
        <div><label>UTM Easting</label><input id="east" inputmode="decimal" value="${p?.utmEasting??''}"></div><div><label>UTM Northing</label><input id="north" inputmode="decimal" value="${p?.utmNorthing??''}"></div>
        <div><label>ارتفاع (متر)</label><input id="alt" inputmode="decimal" value="${p?.altitude??''}"></div><div><label>دقت GPS (متر)</label><input id="acc" inputmode="decimal" value="${p?.accuracy??''}"></div>
      </div>
      <div class="row"><button class="secondary" onclick="v20LL()">WGS84 → UTM</button><button class="secondary" onclick="v20UTM()">UTM → WGS84</button></div>
      <div class="card"><label>نوع نقطه</label><select id="type">${types.map(x=>`<option ${p?.pointType===x?'selected':''}>${escV20(x)}</option>`).join('')}</select><p class="muted">با انتخاب نوع، فرم تخصصی همان نقطه در همین فرم باز می‌شود.</p></div>
      <div class="two"><div><label>وضعیت بستر</label><input id="bed" value="${escV20(p?.bedStatus||'')}"></div><div><label>وضعیت حریم</label><input id="buffer" value="${escV20(p?.bufferStatus||'')}"></div><div><label>وضعیت آبراهه</label><input id="water" value="${escV20(p?.waterwayStatus||'')}"></div><div><label>سطح ریسک</label><select id="risk"><option ${p?.riskLevel==='A'?'selected':''}>A</option><option ${p?.riskLevel==='B'?'selected':''}>B</option><option ${!p||p?.riskLevel==='C'?'selected':''}>C</option></select></div></div>
      <label>نوع تخلف / مورد مشاهده</label><input id="violation" value="${escV20(p?.violationType||'')}"><label>شرح وضعیت</label><textarea id="desc">${escV20(p?.description||'')}</textarea><label>اقدام انجام‌شده</label><textarea id="action">${escV20(p?.action||'')}</textarea>
      <div class="two"><div><label>شماره پرونده</label><input id="caseNo" value="${escV20(p?.caseNumber||'')}"></div><div><label>شماره اخطار</label><input id="warningNo" value="${escV20(p?.warningNumber||'')}"></div><div><label>وضعیت پیگیری</label><input id="follow" value="${escV20(p?.followUpStatus||'')}"></div><div><label>بازدید بعدی</label><input id="next" value="${escV20(p?.nextVisit||'')}" type="date"></div></div>
      <label>کارشناس</label><input id="insp" value="${escV20(p?.inspector||'سالار علی زاده')}">
      <div class="card photo-box"><h3>📷 عکس‌های نقطه</h3><p class="muted">تعداد نامحدود عکس. مختصات UTM روی عکس درج می‌شود.</p><div class="row"><label class="fileBtn">📷 دوربین<input id="photosCamera" type="file" accept="image/*" capture="environment" multiple></label><label class="fileBtn">🖼️ گالری<input id="photosGallery" type="file" accept="image/*" multiple></label></div><div id="photoPreview" class="muted"></div></div>
      <div id="specialHost"></div>
      <div class="row"><button onclick="savePointForm('${editId||''}')">💾 ذخیره نقطه</button><button class="secondary" onclick="exportCurrentSpecialExcel()">📊 Excel این فرم</button><button class="secondary" onclick="show('home')">انصراف</button></div></div>`;
    window._v20Editing=p||null;window._v19Editing=p||null;window._v19EditId=editId||'';
    document.getElementById('type').onchange=()=>renderV20Special(window._v20Editing);
    renderV20Special(p);if(typeof calcUTM==='function')calcUTM();
    ['photosCamera','photosGallery'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{const a=[...(document.getElementById('photosCamera')?.files||[]),...(document.getElementById('photosGallery')?.files||[])];document.getElementById('photoPreview').textContent=a.length?`${a.length} عکس آماده ثبت است.`:''}));
  };
  window.v20LL=function(){window.manualLLGlobal()}; window.v20UTM=function(){window.manualUTMGlobal()};
  window.savePointForm=async function(editId){
    const la=parseFloat(document.getElementById('lat').value),lo=parseFloat(document.getElementById('lon').value);if(!isFinite(la)||!isFinite(lo)){alert('Latitude و Longitude معتبر نیست.');return}
    const r=db.rivers.find(x=>x.id===document.getElementById('river').value);if(!r||!r.active){alert('رودخانه فعال انتخاب کنید.');return}
    window.manualLLGlobal();const u=utm(la,lo),p=editId?db.points.find(x=>x.pointId===editId):null,t=keyV20(document.getElementById('type').value),now=new Date(),id=p?p.pointId:`${r.id}-P-${String(db.points.filter(x=>x.riverId===r.id).length+1).padStart(4,'0')}`;
    const obj={...(p||{}),pointId:id,riverId:r.id,riverName:r.name,date:p?.date||now.toLocaleDateString('fa-IR'),time:p?.time||now.toLocaleTimeString('fa-IR'),latitude:la,longitude:lo,utmZone:Number(document.getElementById('zone').value)||u.zone,utmHemisphere:document.getElementById('hemi').value||(la<0?'S':'N'),utmEasting:Number(document.getElementById('east').value)||u.e,utmNorthing:Number(document.getElementById('north').value)||u.n,altitude:parseFloat(document.getElementById('alt').value)||null,accuracy:parseFloat(document.getElementById('acc').value)||null,pointType:t,bedStatus:document.getElementById('bed').value,bufferStatus:document.getElementById('buffer').value,waterwayStatus:document.getElementById('water').value,violationType:document.getElementById('violation').value,description:document.getElementById('desc').value,action:document.getElementById('action').value,riskLevel:document.getElementById('risk').value,caseNumber:document.getElementById('caseNo').value,warningNumber:document.getElementById('warningNo').value,followUpStatus:document.getElementById('follow').value,nextVisit:document.getElementById('next').value,inspector:document.getElementById('insp').value||'سالار علی زاده',specialData:window.collectSpecialGlobal(t,p?.specialData||{}),updatedAt:now.toISOString(),createdAt:p?.createdAt||now.toISOString(),gpsSource:window.gps?.source||p?.gpsSource||'manual'};
    if(p)Object.assign(p,obj);else db.points.push(obj);
    const files=await collectPhotoFilesV20();let added=0;
    for(const f of files){let data;try{data=await watermarkedUTM(f,{zone:obj.utmZone,hemisphere:obj.utmHemisphere,e:obj.utmEasting,n:obj.utmNorthing,date:obj.date,time:obj.time},id)}catch(e){data=await fileData(f)}const pid='PHOTO-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);await put('photos',{id:pid,pointId:id,riverId:r.id,name:f.name,type:'image/jpeg',originalType:f.type,data,createdAt:now.toISOString(),latitude:la,longitude:lo,utmZone:obj.utmZone,utmHemisphere:obj.utmHemisphere,utmEasting:obj.utmEasting,utmNorthing:obj.utmNorthing,gpsSource:window.gps?.source||'point_capture',date:obj.date,time:obj.time,watermarked:true,watermarkType:'UTM'});added++}
    obj.photoCount=(p?.photoCount||0)+added;await save();alert(added?`نقطه ${id} و ${added} عکس ذخیره شد.`:`نقطه ${id} ذخیره شد.`);show('home');
  };
  function dailyRows(){const today=new Date().toLocaleDateString('fa-IR');const ps=db.points.filter(p=>p.date===today||!p.date);return {today,ps}}
  window.exportDailyReportV20=async function(){const {today,ps}=dailyRows();const sheets=[];sheets.push(['خلاصه روز',[['گزارش پایش روزانه','پایش منابع آب'],['کارشناس','سالار علی زاده'],['تاریخ',today],['تعداد نقاط',ps.length],['تعداد عکس',(db.photos||[]).filter(x=>x.date===today).length],['تعداد پرونده جدید/مرتبط',db.cases.filter(c=>String(c.date||'')===today).length]]]);Object.keys(window.FORM_DEFS).forEach(t=>{const rows=ps.filter(p=>keyV20(p.pointType)===t);if(rows.length)sheets.push([window.FORM_DEFS[t].sheet,specializedRows(t,rows)])});sheets.push(['نقاط پایش',[baseCols(),...ps.map(p=>baseRow(p))]]);sheets.push(['عکس‌ها',[['Photo ID','Point ID','River ID','Date','Time','UTM Zone','Hemisphere','Easting','Northing','Latitude','Longitude','Watermarked'],...(db.photos||[]).filter(x=>x.date===today||ps.some(p=>p.pointId===x.pointId)).map(x=>[x.id,x.pointId,x.riverId,x.date||'',x.time||'',x.utmZone||'',x.utmHemisphere||'',x.utmEasting||'',x.utmNorthing||'',x.latitude||'',x.longitude||'',x.watermarked?'بله':'خیر'])]]);sheets.push(['پرونده‌ها',[['Case ID','Case Number','River','Point ID','Status','Last Action','Latitude','Longitude','UTM Zone','Easting','Northing'],...db.cases.filter(c=>c.date===today||ps.some(p=>p.pointId===c.pointId)).map(c=>[c.id,c.number||'',c.riverName||'',c.pointId||'',c.status||'',c.lastAction||'',c.latitude||'',c.longitude||'',c.utmZone||'',c.utmEasting||'',c.utmNorthing||''])]]);exportSheetsV19(sheets,`گزارش_پایش_روزانه_${today.replace(/[\\/:*?"<>|]/g,'-')}.xlsx`)};
  window.backupTodayV20=async function(){const {today,ps}=dailyRows();const photoObjs=(db.photos||[]).filter(x=>ps.some(p=>p.pointId===x.pointId));const cases=db.cases.filter(c=>ps.some(p=>p.pointId===c.pointId)||String(c.date||'')===today);const tracks=(db.tracks||[]).filter(t=>String(t.start||'').slice(0,10)===new Date().toISOString().slice(0,10)||String(t.date||'')===today);const payload={version:V20,backupType:'daily',date:today,exportedAt:new Date().toISOString(),inspector:'سالار علی زاده',rivers:db.rivers,points:ps,cases,tracks,settings:db.settings,photos:photoObjs};download(JSON.stringify(payload),`Backup_پایش_امروز_${today.replace(/[\\/:*?"<>|]/g,'-')}.json`,'application/json;charset=utf-8');await exportDailyReportV20();alert('پشتیبان امروز و گزارش Excel تولید شد. فایل JSON را به وب‌اپ لپ‌تاپ منتقل و از گزینه «ورود Backup» وارد کنید.');};
  window.importBackupV20=async function(file){try{const text=await file.text(),p=JSON.parse(text);if(p.backupType!=='daily'&&p.version!=='20.0'){alert('این فایل Backup پایش منابع آب نیست.');return}const before={points:db.points.length,cases:db.cases.length,photos:(db.photos||[]).length};const existingP=new Set(db.points.map(x=>x.pointId)),existingC=new Set(db.cases.map(x=>x.id||x.number)),existingR=new Set(db.rivers.map(x=>x.id));(p.rivers||[]).forEach(r=>{if(!existingR.has(r.id))db.rivers.push(r)});(p.points||[]).forEach(x=>{if(!existingP.has(x.pointId))db.points.push(x)});(p.cases||[]).forEach(x=>{const k=x.id||x.number;if(!existingC.has(k))db.cases.push(x)});for(const x of (p.photos||[])){if(x.id&&!(db.photos||[]).some(y=>y.id===x.id))await put('photos',x)}(p.tracks||[]).forEach(t=>{if(t.id&&!(db.tracks||[]).some(x=>x.id===t.id))db.tracks.push(t)});await save();alert(`Backup وارد شد.\nنقطه جدید: ${db.points.length-before.points}\nپرونده جدید: ${db.cases.length-before.cases}\nعکس جدید: ${(db.photos||[]).length-before.photos}`);show('home')}catch(e){console.error(e);alert('ورود Backup انجام نشد. فایل را بررسی کنید.')}};
  window.settingsPage=function(){const s=db.settings||{};app.innerHTML=`<div class="card"><div class="sectionTitle"><h2>⚙️ تنظیمات پایش منابع آب</h2><span class="badge">V20</span></div><div class="two"><div><label>رنگ اصلی</label><input id="v20theme" type="color" value="${escV20(s.theme||'#087ea4')}"></div><div><label>فونت</label><select id="v20font"><option value="NotoApp">Noto Sans Arabic — رسمی</option><option value="Tahoma">Tahoma — اداری</option><option value="Segoe UI">Segoe UI — مدرن</option><option value="Arial">Arial</option></select></div><div><label>گردی کارت‌ها</label><input id="v20radius" type="range" min="8" max="30" value="${Number(s.radius||18)}"></div><div><label>آستانه GPS (متر)</label><input id="v20gps" type="number" min="1" value="${Number(s.gpsAccuracy||20)}"></div></div><button onclick="saveSettingsV20()">💾 ذخیره و اعمال</button><p class="muted">تغییرات روی همین دستگاه ذخیره می‌شوند و پس از Refresh باقی می‌مانند.</p></div><div class="card"><h3>📦 پایان پایش امروز</h3><div class="row"><button onclick="exportDailyReportV20()">📊 گزارش Excel امروز</button><button class="secondary" onclick="backupTodayV20()">📦 Backup امروز</button></div><p class="muted">Backup امروز به‌صورت JSON شامل نقاط، پرونده‌ها، عکس‌ها و پیمایش تولید می‌شود.</p></div><div class="card"><h3>⬆️ انتقال Backup از آیفون</h3><p class="muted">فایل Backup JSON را از آیفون به لپ‌تاپ منتقل کنید و اینجا وارد کنید. اطلاعات قبلی حذف نمی‌شوند و رکورد تکراری وارد نمی‌شود.</p><input type="file" id="backupImportV20" accept="application/json,.json"><button onclick="importBackupV20(document.getElementById('backupImportV20').files[0])">⬆️ ورود Backup</button></div>`;document.getElementById('v20font').value=s.font||'NotoApp'};
  window.saveSettingsV20=async function(){db.settings=db.settings||{};db.settings.theme=document.getElementById('v20theme').value;db.settings.font=document.getElementById('v20font').value;db.settings.radius=Number(document.getElementById('v20radius').value)||18;db.settings.gpsAccuracy=Math.max(1,Number(document.getElementById('v20gps').value)||20);applySettings();await save();alert('تنظیمات با موفقیت ذخیره و اعمال شد.');settingsPage()};
  window.syncCenter=function(){app.innerHTML=`<div class="card"><h2>🔄 انتقال و همگام‌سازی آسان</h2><p>برای پایان هر روز: <b>Backup امروز</b> را بزنید، فایل JSON را به لپ‌تاپ منتقل کنید و سپس <b>ورود Backup</b> را انجام دهید.</p><div class="row"><button onclick="backupTodayV20()">📦 Backup امروز</button><button class="secondary" onclick="settingsPage()">⬆️ ورود Backup</button></div></div>`};
  const oldMore=window.more;window.more=function(){app.innerHTML=`<div class="card"><h2>🧭 مرکز مدیریت</h2><div class="grid"><button onclick="managementReport()">📋 گزارش مدیریتی</button><button onclick="alertsPage()">🔔 هشدار هوشمند</button><button onclick="casesPage()">📁 پرونده‌های زنده</button><button onclick="settingsPage()">⚙️ تنظیمات</button><button onclick="usersPage()">👥 کاربران و امنیت</button><button onclick="syncCenter()">🔄 همگام‌سازی</button><button onclick="photoBank()">📷 بانک عکس</button><button onclick="exportXLSX()">📊 Excel مهندسی</button><button onclick="exportDailyReportV20()">📊 گزارش امروز</button><button onclick="backupTodayV20()">📦 Backup امروز</button><button onclick="exportFullEarthV18()">🌍 KML کامل GIS</button></div></div><div class="card"><h3>🚶 پیمایش</h3><div class="row"><button onclick="startTrack()">شروع</button><button class="danger" onclick="stopTrack()">پایان</button></div></div>`};
  // Make GPS message less noisy while retaining precision sampling.
  window.getGPS=function(){if(!navigator.geolocation){gpsmsg.textContent='GPS در این مرورگر در دسترس نیست.';return}gpsmsg.textContent='در حال دریافت دقیق‌ترین موقعیت…';let best=null,id=navigator.geolocation.watchPosition(pos=>{if(!best||pos.coords.accuracy<best.coords.accuracy)best=pos; if(best&&best.coords.accuracy<=Math.max(5,Number(db.settings?.gpsAccuracy||20))){navigator.geolocation.clearWatch(id);const c=best.coords;lat.value=c.latitude.toFixed(9);lon.value=c.longitude.toFixed(9);alt.value=c.altitude==null?'':c.altitude.toFixed(2);acc.value=c.accuracy.toFixed(2);calcUTM();window.gps={latitude:c.latitude,longitude:c.longitude,altitude:c.altitude,accuracy:c.accuracy,source:'device_gps'};gpsmsg.textContent=`GPS ثبت شد | دقت ${c.accuracy.toFixed(1)} متر`}},e=>gpsmsg.textContent='خطای GPS: '+e.message,{enableHighAccuracy:true,maximumAge:0,timeout:15000});setTimeout(()=>{navigator.geolocation.clearWatch(id);if(best&&!lat.value){const c=best.coords;lat.value=c.latitude.toFixed(9);lon.value=c.longitude.toFixed(9);alt.value=c.altitude==null?'':c.altitude.toFixed(2);acc.value=c.accuracy.toFixed(2);calcUTM();window.gps={latitude:c.latitude,longitude:c.longitude,altitude:c.altitude,accuracy:c.accuracy,source:'device_gps'};gpsmsg.textContent=`GPS ثبت شد | دقت ${c.accuracy.toFixed(1)} متر`}},12000)};
  window.V20={version:V20,forms:Object.keys(window.FORM_DEFS),inspector:'سالار علی زاده'};
})();
