
/* V24: management/reporting/GIS/manual-history/backup/Excel/navigation hardening */
(function(){
  const V24='24.0';
  const esc=x=>typeof window.esc==='function'?window.esc(x):String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const todayFa=()=>new Date().toLocaleDateString('fa-IR');
  const normDigits=s=>String(s??'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/-/g,'/');
  const isToday=v=>{const x=normDigits(v).split('/').map(Number);const t=normDigits(todayFa()).split('/').map(Number);return x.length===3&&t.length===3&&x[0]===t[0]&&x[1]===t[1]&&x[2]===t[2]};
  const cleanName=x=>String(x||'').replace(/[\\/:*?"<>|]/g,'_').slice(0,80);
  const allPhotos=async()=>{try{return await getAll('photos')}catch(e){return db.photos||[]}};

  // Better quick actions: only New Point + Patrol.
  window.quickActionsV24=function(){
    app.innerHTML=`<div class="card quick-v24"><div class="sectionTitle"><h2>⚡ عملیات سریع</h2><span class="badge">دو اقدام اصلی</span></div><div class="quickGrid"><button onclick="show('new')"><span>📍</span><b>ثبت نقطه جدید</b><small>GPS / UTM / فرم تخصصی / عکس</small></button><button onclick="show('more');setTimeout(()=>document.getElementById('trackPanelV24')?.scrollIntoView({behavior:'smooth'}),50)"><span>🚶</span><b>پیمایش</b><small>شروع و پایان مسیر و ذخیره Track</small></button></div></div>`;
  };

  // Manual forms + historical records explorer.
  window.manualHistoricalV24=function(){
    const defs=window.FORM_DEFS||{};
    const sheets=(db.historical||[]);
    const opts=Object.keys(defs).map(k=>`<option value="${esc(k)}">${esc(defs[k].sheet||k)}</option>`).join('');
    app.innerHTML=`<div class="card"><div class="sectionTitle"><h2>📝 فرم دستی و سوابق سنواتی</h2><span class="badge">V24</span></div><p class="muted">فرم‌های تخصصی همین‌جا انتخاب می‌شوند. سوابق سنواتی موجود در برنامه نیز قابل جستجو و مشاهده هستند.</p><div class="tabs"><button id="mhTabForm" class="active" onclick="mhTab('form')">فرم دستی</button><button id="mhTabHist" onclick="mhTab('hist')">سوابق سنواتی</button></div><div id="mhBody"></div></div>`;
    window.mhTab=function(tab){document.getElementById('mhTabForm')?.classList.toggle('active',tab==='form');document.getElementById('mhTabHist')?.classList.toggle('active',tab==='hist');if(tab==='form')renderManualForm();else renderHist();};
    function renderManualForm(){
      const first=Object.keys(defs)[0]||'';
      document.getElementById('mhBody').innerHTML=`<label>نوع فرم</label><select id="mhType">${opts}</select><div id="mhFields"></div><div class="row"><button onclick="saveManualRecordV24()">💾 ذخیره رکورد دستی</button><button class="secondary" onclick="exportManualV24()">📊 خروجی Excel</button></div>`;
      document.getElementById('mhType').value=first;renderManualFields();document.getElementById('mhType').onchange=renderManualFields;
    }
    function renderManualFields(){const t=document.getElementById('mhType')?.value,d=defs[t];const host=document.getElementById('mhFields');if(!host||!d)return;const f=typeof window.formFieldsGlobal==='function'?window.formFieldsGlobal(d,{}):'';host.innerHTML=`<div class="card"><h3>فرم ${esc(d.sheet||t)}</h3><div class="two">${f}</div></div>`;setTimeout(()=>yesNoV24(host),0)}
    function renderHist(){
      document.getElementById('mhBody').innerHTML=`<label>جستجو در سوابق</label><input id="mhSearch" placeholder="نام رودخانه، پرونده، شماره، مختصات..." oninput="renderHistV24()"><div id="mhHistList"></div>`;renderHistV24();
    }
    window.renderHistV24=function(){const q=String(document.getElementById('mhSearch')?.value||'').trim().toLowerCase();let html='';for(const sh of sheets){const rows=(sh.rows||[]).slice(1);const hits=q?rows.filter(r=>r.some(v=>String(v??'').toLowerCase().includes(q))):rows.slice(0,30);if(!hits.length)continue;html+=`<div class="card"><div class="sectionTitle"><h3>🗂 ${esc(sh.sheet)}</h3><span class="badge">${rows.length.toLocaleString('fa-IR')} ردیف</span></div><div class="tablewrap"><table class="v24table"><thead><tr>${(sh.rows?.[0]||[]).slice(0,12).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${hits.slice(0,30).map(r=>`<tr>${r.slice(0,12).map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${rows.length>30?'<p class="muted">برای نمایش سریع، حداکثر ۳۰ ردیف اول/منطبق نمایش داده می‌شود.</p>':''}</div>`}if(!html)html='<div class="card muted">رکوردی پیدا نشد.</div>';document.getElementById('mhHistList').innerHTML=html;};
    window.saveManualRecordV24=function(){const t=document.getElementById('mhType')?.value,d=defs[t];if(!d)return;const data={};(d.fields||[]).forEach((f,i)=>{const el=document.getElementById('sf_'+i);if(el)data[f[0]]=el.value});db.manualRecords=db.manualRecords||[];db.manualRecords.push({id:'MAN-'+Date.now(),type:t,sheet:d.sheet,data,date:todayFa(),inspector:'سالار علی زاده',source:'فرم دستی'});save().then(()=>{alert('رکورد دستی ذخیره شد.');})};
    window.exportManualV24=function(){const rows=[['ID','Type','Sheet','Date','Inspector','Field','Value']];(db.manualRecords||[]).forEach(r=>Object.entries(r.data||{}).forEach(([k,v])=>rows.push([r.id,r.type,r.sheet,r.date,r.inspector,k,v])));downloadXLSX([['فرم‌های دستی',rows]],'فرم_دستی_پایش_منابع_آب.xlsx')};
    mhTab('form');
  };

  // Turn suitable specialized text inputs into Yes/No choices, preserving their ids for existing collectors.
  function yesNoV24(root){
    const words=['مجوز','دارای مجوز','وضعیت مجوز','قانونی','غیرمجاز','فعال','متوقف','اتصال به شبکه','آبفروشی مجاز','پروانه','اجازه','استفاده از آب','تجهیزات','انسداد','رفع تصرف','اخطار داده شد','تخلیه شد'];
    root.querySelectorAll('label').forEach(l=>{const txt=l.textContent.trim();if(!words.some(w=>txt.includes(w)))return;const wrap=l.parentElement;const inp=wrap?.querySelector('input');if(!inp||inp.tagName==='SELECT'||inp.type==='date'||inp.type==='number')return;const sel=document.createElement('select');sel.id=inp.id;sel.name=inp.name||inp.id;sel.innerHTML='<option value="">انتخاب کنید</option><option value="بله">بله</option><option value="خیر">خیر</option>';sel.value=inp.value||'';inp.replaceWith(sel);});
  }
  const oldRender=window.renderSpecial22;window.renderSpecial22=function(p){oldRender?.(p);setTimeout(()=>{const h=document.getElementById('specialForm');if(h)yesNoV24(h)},0)};

  // Daily report: date matching works with Persian/Arabic digits and produces useful management sheets.
  window.exportDailyReportV24=async function(){
    try{
      const ps=(db.points||[]).filter(p=>isToday(p.date)||isToday(p.createdAt));
      const photos=(await allPhotos()).filter(x=>isToday(x.date)||ps.some(p=>p.pointId===x.pointId));
      const cases=(db.cases||[]).filter(c=>isToday(c.date)||ps.some(p=>p.pointId===c.pointId));
      const tracks=(db.tracks||[]).filter(t=>isToday(t.date)||isToday(t.start));
      const byType={};ps.forEach(p=>(byType[p.pointType]=byType[p.pointType]||[]).push(p));
      const summary=[['گزارش عملکرد روزانه','پایش منابع آب'],['تاریخ',todayFa()],['کارشناس','سالار علی زاده'],['تعداد نقاط',ps.length],['تعداد عکس',photos.length],['تعداد پرونده مرتبط',cases.length],['تعداد پیمایش',tracks.length],['ریسک A',ps.filter(p=>p.riskLevel==='A').length],['ریسک B',ps.filter(p=>p.riskLevel==='B').length],['ریسک C',ps.filter(p=>p.riskLevel==='C').length]];
      const pointRows=[['Point ID','River','Date','Time','Type','Risk','Latitude','Longitude','UTM Zone','Hemisphere','Easting','Northing','Violation','Description','Action','Follow-up','Inspector','Photo Count'],...ps.map(p=>[p.pointId,p.riverName,p.date,p.time,p.pointType,p.riskLevel,p.latitude,p.longitude,p.utmZone,p.utmHemisphere,p.utmEasting,p.utmNorthing,p.violationType,p.description,p.action,p.followUpStatus,p.inspector,p.photoCount||0])];
      const photoRows=[['Photo ID','Point ID','River','Date','Time','Filename','Latitude','Longitude','UTM Zone','Hemisphere','Easting','Northing','Watermarked'],...photos.map(x=>[x.id,x.pointId,x.riverId,x.date,x.time,x.name,x.latitude,x.longitude,x.utmZone,x.utmHemisphere,x.utmEasting,x.utmNorthing,x.watermarked?'بله':'خیر'])];
      const caseRows=[['Case ID','Number','River','Point ID','Date','Status','Last Action','Latitude','Longitude','UTM Zone','Easting','Northing'],...cases.map(c=>[c.id,c.number,c.riverName,c.pointId,c.date,c.status,c.lastAction,c.latitude,c.longitude,c.utmZone,c.utmEasting,c.utmNorthing])];
      const sheets=[['خلاصه روز',summary],['نقاط امروز',pointRows],['عکس‌های امروز',photoRows],['پرونده‌های مرتبط',caseRows],['پیمایش‌ها',[['Track ID','River','Start','End','Point Count'],...tracks.map(t=>[t.id,t.riverId,t.start,t.end||'',(t.points||[]).length])]]];
      Object.keys(byType).forEach(t=>{const d=window.FORM_DEFS?.[t];if(d&&typeof window.specializedRowsGlobal==='function')sheets.push([d.sheet,window.specializedRowsGlobal(t,byType[t])])});
      downloadXLSX(sheets,`گزارش_پایش_امروز_${cleanName(todayFa())}.xlsx`);
    }catch(e){console.error(e);alert('گزارش امروز ساخته نشد: '+(e.message||e))}
  };

  // Full engineering workbook modeled on the earlier engineering workbook structure.
  window.exportEngineeringV24=async function(){
    try{
      const photos=await allPhotos();
      const points=db.points||[],cases=db.cases||[],tracks=db.tracks||[];
      const riverRows=[['River ID','River Name','Province','County','Active','Points','Cases','High Risk A','Latest Visit'],...db.rivers.map(r=>{const ps=points.filter(p=>p.riverId===r.id);return[r.id,r.name,r.province||'',r.county||'',r.active?'بله':'خیر',ps.length,cases.filter(c=>c.riverId===r.id).length,ps.filter(p=>p.riskLevel==='A').length,ps.map(p=>p.date).filter(Boolean).sort().slice(-1)[0]||'']})];
      const pointRows=[['Point ID','River ID','River Name','Date','Time','Latitude','Longitude','UTM Zone','UTM Hemisphere','UTM Easting','UTM Northing','Altitude','GPS Accuracy','Point Type','Bed Status','Buffer Status','Waterway Status','Violation Type','Description','Action','Risk Level','Case ID','Case Number','Warning Number','Follow-up Status','Next Visit','Inspector','Photo Count','GPS Source','Source','Created At','Updated At'],...points.map(p=>[p.pointId,p.riverId,p.riverName,p.date,p.time,p.latitude,p.longitude,p.utmZone,p.utmHemisphere,p.utmEasting,p.utmNorthing,p.altitude,p.accuracy,p.pointType,p.bedStatus,p.bufferStatus,p.waterwayStatus,p.violationType,p.description,p.action,p.riskLevel,p.caseId,p.caseNumber,p.warningNumber,p.followUpStatus,p.nextVisit,p.inspector,p.photoCount,p.gpsSource,p.source,p.createdAt,p.updatedAt])];
      const photoRows=[['Photo ID','Point ID','River ID','Filename','Date','Time','Latitude','Longitude','UTM Zone','Hemisphere','Easting','Northing','GPS Source','Watermarked'],...photos.map(p=>[p.id,p.pointId,p.riverId,p.name,p.date,p.time,p.latitude,p.longitude,p.utmZone,p.utmHemisphere,p.utmEasting,p.utmNorthing,p.gpsSource,p.watermarked?'بله':'خیر'])];
      const caseRows=[['Case ID','Case Number','Warning Number','River','Point ID','Date','Owner','Violation','Status','Last Action','Latitude','Longitude','UTM Zone','Hemisphere','Easting','Northing','Source Sheet','Source Row'],...cases.map(c=>[c.id,c.number,c.warningNumber,c.riverName,c.pointId,c.date,c.owner,c.violationType,c.status,c.lastAction,c.latitude,c.longitude,c.utmZone,c.utmHemisphere,c.utmEasting,c.utmNorthing,c.sourceSheet,c.sourceRow])];
      const trackRows=[['Track ID','River ID','Start','End','Point Count','Status'],...tracks.map(t=>[t.id,t.riverId,t.start,t.end||'',(t.points||[]).length,t.status||'ذخیره‌شده'])];
      const insp=[['Inspector','Points','Photos','High Risk A'],['سالار علی زاده',points.filter(p=>p.inspector==='سالار علی زاده'||!p.inspector).length,photos.length,points.filter(p=>p.riskLevel==='A').length]];
      const lookup=[['Risk','A','B','C'],['Point Types',...(window.TYPES||[])],['Specialized Forms',...Object.keys(window.FORM_DEFS||{})],['Case Statuses','باز','در حال پیگیری','مختومه'],['Yes/No','بله','خیر']];
      const dash=[['شاخص','مقدار'],['تاریخ تولید',new Date().toLocaleString('fa-IR')],['رودخانه‌ها',db.rivers.length],['رودخانه فعال',db.rivers.filter(r=>r.active).length],['نقاط',points.length],['ریسک A',points.filter(p=>p.riskLevel==='A').length],['ریسک B',points.filter(p=>p.riskLevel==='B').length],['ریسک C',points.filter(p=>p.riskLevel==='C').length],['پرونده‌ها',cases.length],['پرونده باز',cases.filter(c=>c.status!=='مختومه').length],['عکس‌ها',photos.length],['پیمایش‌ها',tracks.length],['سوابق سنواتی',db.historical.reduce((a,s)=>a+Math.max(0,(s.rows||[]).length-1),0)]];
      const sheets=[['Dashboard',dash],['Rivers',riverRows],['Points',pointRows],['Photos',photoRows],['Cases',caseRows],['Tracks',trackRows],['Inspectors',insp],['Lookup Data',lookup],['Historical Summary',[['Sheet','Rows'],...(db.historical||[]).map(s=>[s.sheet,Math.max(0,(s.rows||[]).length-1)])]],['Historical Records',[['Sheet','Source Row','Field 1','Field 2','Field 3','Field 4','Field 5','Field 6','Field 7','Field 8','Field 9','Field 10','Field 11','Field 12'],...(db.historical||[]).flatMap(s=>(s.rows||[]).slice(1).map((r,i)=>[s.sheet,i+2,...r.slice(0,12)]))]]];
      Object.keys(window.FORM_DEFS||{}).forEach(t=>{const ps=points.filter(p=>String(p.pointType||'')===String(t));if(ps.length&&typeof window.specializedRowsGlobal==='function')sheets.push([window.FORM_DEFS[t].sheet,window.specializedRowsGlobal(t,ps)])});
      downloadXLSX(sheets,'پایش_منابع_آب_Engineering_Final_V24.xlsx');
    }catch(e){console.error(e);alert('Excel مهندسی ساخته نشد: '+(e.message||e))}
  };

  // Complete backup ZIP with JSON + Excel + real photo files. JSON is also separately importable.
  window.backupFullV24=async function(){
    try{
      const photos=await allPhotos();
      const payload={version:V24,backupType:'full',exportedAt:new Date().toISOString(),date:todayFa(),inspector:'سالار علی زاده',rivers:db.rivers,points:db.points,cases:db.cases,tracks:db.tracks,settings:db.settings,manualRecords:db.manualRecords||[],photos:photos.map(p=>({...p,data:undefined,hasFile:true}))};
      const files=[{name:'backup/Backup_کامل_پایش_منابع_آب.json',data:JSON.stringify(payload)}, {name:'backup/README.txt',data:'این پشتیبان شامل اطلاعات JSON و فایل‌های واقعی عکس است. برای ورود به برنامه، فایل JSON را از داخل ZIP استخراج و از گزینه ورود Backup انتخاب کنید.'}];
      for(const p of photos){if(p.data)files.push({name:'photos/'+cleanName(p.pointId||'unknown')+'/'+cleanName(p.name||p.id)+'.jpg',data:base64ToBytes(p.data)})}
      const zip=zipStore(files);download(zip,'Backup_کامل_پایش_منابع_آب_V24.zip','application/zip');
      const jsonFile=JSON.stringify({...payload,photos});download(jsonFile,'Backup_قابل_ورود_پایش_منابع_آب_V24.json','application/json;charset=utf-8');
    }catch(e){console.error(e);alert('پشتیبان کامل ساخته نشد: '+(e.message||e))}
  };
  function base64ToBytes(data){const b64=String(data).split(',').pop();const bin=atob(b64);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}

  // Stronger management report with river, risk, case, photo, data-quality and historical sections.
  window.managementReportV24=function(){
    const ps=db.points||[],cs=db.cases||[],r=db.rivers||[],photos=db.photos||[];const open=cs.filter(c=>c.status!=='مختومه');
    const riverRows=r.map(x=>{const q=ps.filter(p=>p.riverId===x.id);return`<tr><td>${esc(x.name)}</td><td>${q.length}</td><td>${q.filter(p=>p.riskLevel==='A').length}</td><td>${q.filter(p=>p.riskLevel==='B').length}</td><td>${q.filter(p=>p.riskLevel==='C').length}</td><td>${cs.filter(c=>c.riverId===x.id).length}</td></tr>`}).join('');
    const violations={};ps.forEach(p=>{const k=p.violationType||p.pointType||'بدون عنوان';violations[k]=(violations[k]||0)+1});const top=Object.entries(violations).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>`<li>${esc(x[0])}: <b>${x[1]}</b></li>`).join('');
    const quality=[['نقاط بدون مختصات',ps.filter(p=>!isFinite(Number(p.latitude))||!isFinite(Number(p.longitude))).length],['نقاط بدون UTM',ps.filter(p=>!p.utmEasting||!p.utmNorthing).length],['نقاط بدون عکس',ps.filter(p=>!(p.photoCount>0)).length],['پرونده باز',open.length],['ریسک A',ps.filter(p=>p.riskLevel==='A').length],['عکس‌های بانک',photos.length],['سوابق سنواتی',db.historical.reduce((a,s)=>a+Math.max(0,(s.rows||[]).length-1),0)]];
    app.innerHTML=`<div class="card management-v24"><div class="sectionTitle"><h2>📋 گزارش مدیریتی جامع</h2><span class="badge">قابل چاپ / PDF</span></div><p class="muted">تهیه‌شده در ${esc(new Date().toLocaleString('fa-IR'))} — کارشناس: سالار علی زاده</p><div class="grid"><div class="stat"><b>${r.length}</b>رودخانه</div><div class="stat"><b>${ps.length}</b>نقطه</div><div class="stat"><b>${ps.filter(p=>p.riskLevel==='A').length}</b>ریسک A</div><div class="stat"><b>${open.length}</b>پرونده باز</div></div><h3>تفکیک رودخانه‌ای</h3><div class="tablewrap"><table class="v24table"><thead><tr><th>رودخانه</th><th>نقاط</th><th>A</th><th>B</th><th>C</th><th>پرونده</th></tr></thead><tbody>${riverRows||'<tr><td colspan="6">داده‌ای نیست</td></tr>'}</tbody></table></div><h3>موارد پرتکرار</h3><ul>${top||'<li>داده‌ای ثبت نشده</li>'}</ul><h3>کنترل کیفیت</h3><ul>${quality.map(x=>`<li>${esc(x[0])}: <b>${x[1]}</b></li>`).join('')}</ul><div class="row"><button onclick="window.print()">🖨 چاپ / ذخیره PDF</button><button class="secondary" onclick="exportManagementV24()">📊 Excel گزارش مدیریتی</button></div></div>`;
  };
  window.exportManagementV24=function(){const ps=db.points||[],cs=db.cases||[];const river=[['رودخانه','نقاط','A','B','C','پرونده'],...db.rivers.map(r=>{const q=ps.filter(p=>p.riverId===r.id);return[r.name,q.length,q.filter(p=>p.riskLevel==='A').length,q.filter(p=>p.riskLevel==='B').length,q.filter(p=>p.riskLevel==='C').length,cs.filter(c=>c.riverId===r.id).length]})];const risk=[['Point ID','River','Date','Type','Risk','Violation','Description','Action','Follow-up'],...ps.filter(p=>p.riskLevel==='A').map(p=>[p.pointId,p.riverName,p.date,p.pointType,p.riskLevel,p.violationType,p.description,p.action,p.followUpStatus])];const cases=[['Case ID','Number','River','Date','Status','Last Action','Point ID'],...cs.map(c=>[c.id,c.number,c.riverName,c.date,c.status,c.lastAction,c.pointId])];downloadXLSX([['خلاصه مدیریتی',[['شاخص','مقدار'],['رودخانه‌ها',db.rivers.length],['نقاط',ps.length],['ریسک A',ps.filter(p=>p.riskLevel==='A').length],['پرونده باز',cs.filter(c=>c.status!=='مختومه').length]]],['تفکیک رودخانه‌ای',river],['ریسک A',risk],['پرونده‌ها',cases]],'گزارش_مدیریتی_پایش_منابع_آب.xlsx')};

  // Better GIS map with independent layer controls for points, river bed/buffer and cases.
  window.mapPageV24=function(){
    app.innerHTML=`<div class="card"><div class="sectionTitle"><h2>🗺 نقشه مهندسی حریم و بستر</h2><span class="badge">GIS</span></div><div id="mapV24" style="height:520px;border-radius:16px;overflow:hidden"></div><div class="row mapTools"><button onclick="toggleMapLayerV24('bed')">حریم و بستر</button><button onclick="toggleMapLayerV24('points')">نقاط پایش</button><button onclick="toggleMapLayerV24('cases')">پرونده‌ها</button><button class="secondary" onclick="downloadBedBufferKML()">⬇️ KML حریم و بستر</button><button class="secondary" onclick="exportFullEarthV18()">🌍 KML کامل GIS</button></div><p class="muted">لایه‌ها مستقل هستند؛ با روشن/خاموش کردن هر لایه می‌توان محدوده حریم و بستر، نقاط پایش و پرونده‌ها را جداگانه بررسی کرد.</p></div><div class="card"><h3>فیلتر نقشه</h3><div class="two"><div><label>رودخانه</label><select id="mapRiverV24"><option value="">همه رودخانه‌ها</option>${(db.rivers||[]).map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></div><div><label>ریسک</label><select id="mapRiskV24"><option value="">همه</option><option>A</option><option>B</option><option>C</option></select></div></div><button onclick="refreshMapPointsV24()">اعمال فیلتر</button></div>`;
    if(typeof L==='undefined'){document.getElementById('mapV24').innerHTML='<div class="card">برای نمایش نقشه، اتصال اینترنت لازم است.</div>';return}
    window.v24Map=L.map('mapV24').setView([35.65,52.35],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(v24Map);
    window.v24Layers={points:L.layerGroup().addTo(v24Map),cases:L.layerGroup().addTo(v24Map),bed:L.layerGroup().addTo(v24Map)};
    refreshMapPointsV24();loadMapBoundaryV24();
  };
  window.refreshMapPointsV24=function(){if(!window.v24Layers)return;v24Layers.points.clearLayers();v24Layers.cases.clearLayers();const rid=document.getElementById('mapRiverV24')?.value||'',risk=document.getElementById('mapRiskV24')?.value||'';for(const p of db.points||[]){if(!isFinite(Number(p.latitude))||!isFinite(Number(p.longitude))||(rid&&p.riverId!==rid)||(risk&&p.riskLevel!==risk))continue;const m=L.circleMarker([p.latitude,p.longitude],{radius:p.riskLevel==='A'?9:7,color:p.riskLevel==='A'?'#c62828':p.riskLevel==='B'?'#ef8b00':'#1565c0',fillOpacity:.85}).bindPopup(`<b>${esc(p.pointType)}</b><br>${esc(p.pointId)}<br>رودخانه: ${esc(p.riverName)}<br>ریسک: ${esc(p.riskLevel)}<br>UTM: ${esc(p.utmZone)}${esc(p.utmHemisphere)} / ${esc(p.utmEasting)} / ${esc(p.utmNorthing)}<br><button onclick="editPoint('${esc(p.pointId)}')">ویرایش</button>`);m.addTo(v24Layers.points)}for(const c of db.cases||[]){const q=typeof caseCoord==='function'?caseCoord(c):null;if(!q||!isFinite(q.lat)||!isFinite(q.lon)||(rid&&c.riverId!==rid))continue;L.circleMarker([q.lat,q.lon],{radius:6,color:'#7b1fa2',fillOpacity:.75}).bindPopup(`<b>پرونده ${esc(c.number||c.id)}</b><br>${esc(c.riverName||'')}<br>${esc(c.status||'')}`).addTo(v24Layers.cases)}};
  async function loadMapBoundaryV24(){try{const r=await fetch('data/boundary.geojson?cb='+Date.now());if(r.ok){const gj=await r.json();L.geoJSON(gj,{style:{color:'#1565c0',weight:2,fillOpacity:.05},onEachFeature:(f,l)=>l.bindPopup(`<b>${esc(f.properties?.name||'حریم و بستر')}</b><br>${esc(f.properties?.description||'')}`)}).addTo(v24Layers.bed)} }catch(e){}try{const r=await fetch('data/bed_buffer.kml?cb='+Date.now());if(r.ok&&typeof kmlTextToGeoJSON==='function'){const gj=kmlTextToGeoJSON(await r.text());L.geoJSON(gj,{style:{color:'#00897b',weight:2,fillOpacity:.03},onEachFeature:(f,l)=>l.bindPopup(`<b>${esc(f.properties?.name||'لایه حریم و بستر')}</b>`)}).addTo(v24Layers.bed)}}catch(e){console.warn(e)}}
  window.toggleMapLayerV24=function(k){if(!v24Layers)return;const l=v24Layers[k];if(v24Map.hasLayer(l))v24Map.removeLayer(l);else v24Map.addLayer(l)};

  // More page: management tools separated from quick actions.
  window.moreV24=function(){app.innerHTML=`<div class="card"><div class="sectionTitle"><h2>🧭 مرکز مدیریت</h2><span class="badge">V24</span></div><div class="toolGrid"><button onclick="managementReportV24()">📋 گزارش مدیریتی</button><button onclick="manualHistoricalV24()">📝 فرم دستی / سنواتی</button><button onclick="window.photoBank()">📷 بانک عکس</button><button onclick="exportEngineeringV24()">📊 Excel مهندسی</button><button onclick="exportDailyReportV24()">📅 گزارش امروز</button><button onclick="backupFullV24()">💾 Backup کامل + عکس</button><button onclick="syncCenter()">🔄 انتقال / ورود Backup</button><button onclick="window.exportFullEarthV18()">🌍 KML کامل GIS</button><button onclick="settingsPage()">⚙️ تنظیمات</button><button onclick="usersPage()">👥 کاربران</button></div></div><div id="trackPanelV24" class="card"><h3>🚶 پیمایش</h3><div class="row"><button onclick="startTrack()">شروع پیمایش</button><button class="danger" onclick="stopTrack()">پایان پیمایش</button></div><p class="muted">پیمایش ذخیره‌شده: ${(db.tracks||[]).length}</p></div>`};

  // Replace the lower navigation with a cleaner 5-item layout: خانه، نقطه، نقشه، مدیریت، بیشتر.
  function polishNav(){const n=document.querySelector('.nav');if(!n)return;n.innerHTML='<button data-p="home" onclick="show(\'home\')"><span>⌂</span>خانه</button><button data-p="new" onclick="show(\'new\')"><span>📍</span>ثبت نقطه</button><button data-p="map" onclick="show(\'map\')"><span>🗺</span>نقشه</button><button data-p="more" onclick="moreV24()"><span>📊</span>مدیریت</button><button data-p="more" onclick="moreV24()"><span>☰</span>بیشتر</button>';}
  const oldShow=window.show;window.show=function(p){nav(p);if(p==='home'){home();return}if(p==='new'){window.newPoint();return}if(p==='map'){window.mapPageV24();return}if(p==='more'){nav('more');moreV24();return}oldShow(p);};
  window.mapPage=window.mapPageV24;
  window.managementReport=window.managementReportV24;
  // Home quick section override: only two quick actions, while keeping dashboard.
  const oldHome=window.home;window.home=function(){oldHome();setTimeout(()=>{const appEl=document.getElementById('app');const cards=[...appEl.querySelectorAll('.card')];const quick=cards.find(c=>c.innerText.includes('عملیات سریع'));if(quick){quick.innerHTML='<div class="sectionTitle"><h3>⚡ عملیات سریع</h3><span class="badge">فقط دو اقدام</span></div><div class="quickGrid"><button onclick="show(\'new\')"><span>📍</span><b>ثبت نقطه جدید</b><small>GPS / UTM / فرم تخصصی / عکس</small></button><button onclick="moreV24();setTimeout(()=>document.getElementById(\'trackPanelV24\')?.scrollIntoView({behavior:\'smooth\'}),50)"><span>🚶</span><b>پیمایش</b><small>شروع و پایان مسیر</small></button></div>';}else{const c=document.createElement('div');c.dataset.v24Quick='1';c.className='card';c.innerHTML='<div class="sectionTitle"><h3>⚡ عملیات سریع</h3><span class="badge">فقط دو اقدام</span></div><div class="quickGrid"><button onclick="show(\'new\')"><span>📍</span><b>ثبت نقطه جدید</b><small>GPS / UTM / فرم تخصصی / عکس</small></button><button onclick="moreV24()"><span>🚶</span><b>پیمایش</b><small>شروع و پایان مسیر</small></button></div>';appEl?.insertBefore(c,appEl.firstChild?.nextSibling||null)}},40)};
  // Settings: preserve existing settings but expose the new report/backup tools.
  const oldSettings=window.settingsPage;window.settingsPage=function(){oldSettings();setTimeout(()=>{const box=document.createElement('div');box.className='card';box.innerHTML='<h3>📦 خروجی‌های حرفه‌ای</h3><div class="row"><button onclick="exportDailyReportV24()">گزارش امروز</button><button onclick="exportEngineeringV24()">Excel مهندسی</button><button onclick="backupFullV24()">Backup کامل + عکس</button></div>';document.getElementById('app')?.appendChild(box)},30)};
  // Styles
  const st=document.createElement('style');st.textContent=`.quickGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.quickGrid button,.toolGrid button{display:flex;flex-direction:column;align-items:center;gap:5px;padding:16px;background:linear-gradient(145deg,#087ea4,#00a8c8);box-shadow:0 8px 18px #087ea42b}.quickGrid span{font-size:28px}.quickGrid small{font-size:10px;opacity:.9}.toolGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.toolGrid button{min-height:78px}.v24table{border-collapse:collapse;width:100%;font-size:11px}.v24table th,.v24table td{border:1px solid #d8e7eb;padding:7px;white-space:nowrap}.v24table th{background:#eaf6f9}.mapTools{margin-top:8px}.bottom{padding-top:8px}.nav button{border-radius:14px}.nav button.active{background:#e7f6fa}.nav span{font-size:18px}.compact-gps{grid-template-columns:repeat(4,1fr)}@media(max-width:650px){.quickGrid,.toolGrid{grid-template-columns:1fr 1fr}.compact-gps{grid-template-columns:1fr 1fr}}@media(min-width:800px){.toolGrid{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(st);
  polishNav();
  window.V24={version:V24};
})();
